language: c
compiler:
  - gcc
  - clang
notifications:
  recipients:
    - kenhys@gmail.com
branches:
  only:
    - master
    - develop
before_script:
  - curl https://raw.githubusercontent.com/kenhys/sylpheed-plugin-factory/master/misc/travis/sylplugin-factory.sh | sh
  - ./autogen.sh
script:
  - curl https://raw.githubusercontent.com/kenhys/sylpheed-plugin-factory/master/misc/travis/configure.sh | sh
  - make

